name: CropPlus
main:  com.github.schooluniform.cropplus.CropPlus
version: 0.0.8
author: miSkYle
softdepend: [RealSurvival]
api-version: 1.13
commands:
  crop:
      description: CropPlus
      usage: /<command> reload
permissions: 
  CropPlus.admin:
    description: Use Admin's Commands
    default: op