name: CropPlus
main:  com.github.schooluniform.cropplus.CropPlus
version: 0.0.6
author: School_Uniform
depend: [RealSurvival]
commands:
  crop:
      description: CropPlus
      usage: /<command>
permissions: 
  CropPlus.admin:
    description: Use Admin's Commands
    default: op